### ISSUE TITLE
Introduce Sass Maps to declare variable groups

### ISSUE THREAD

**Issue by deioo** [alphasights/paint#32]
A very basic use case scenario would be e.g an alert-colour map:
```scss
$alert-colors: (
  'alert': (
    text: $white,
    border: darken($alert-color, 10%),
    background: $alert-color
  ),
  'warning': (
    text: $white,
    border: darken($warning-color, 10%),
    background: $warning-color
  ),
  'info': (
    text: $white,
    border: darken($info-color, 10%),
    background: $info-color
  )
);
```
and create a mixin to fetch those colours easily
```scss
@function alert-color($color-name, $shade: background) {
    @return map-get(map-get($colors, $color-name), $shade);
}
```

then fetch it easily like
```scss
%alert-box {
  background: alert-color('alert');
  color: alert-color('alert', 'text');
}
```

But we could also use it to define component properties and even a basic colour set that use different shades, e.g primary-color-light, primary-color-dark, primary-color
